// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SakilaCountry.Data;

namespace SakilaCountry.Migrations
{
    [DbContext(typeof(SakilaCountryContext))]
    partial class SakilaCountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SakilaCountry.Models.Country", b =>
                {
                    b.Property<short?>("country_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Extraterrestrials");

                    b.Property<string>("country");

                    b.Property<DateTime>("last_update");

                    b.HasKey("country_id");

                    b.ToTable("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
